name: "Maven Deploy"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v4"

    - name: "Set up JDK 1.8"
      uses: "actions/setup-java@v4.2.0"
      with:
        java-version: "8.0.302+8"
        distribution: "temurin"

    - name: "Set up Maven settings file"
      uses: "s4u/maven-settings-action@v3.0.0"
      with:
        servers: '[{"id": "jasonkaranik-nexus", "username": "${{ secrets.NEXUS_USERNAME }}", "password": "${{ secrets.NEXUS_PASSWORD }}"}]'
      
    - name: "Build and Deploy"
      run: "mvn clean deploy -Dmaven.test.skip=true -Dmaven.install.skip=true -Dhttps.protocols=TLSv1.2 > /dev/null 2>&1"

